### ISSUE TITLE
CLI replication when creating local maps

### ISSUE THREAD

**Issue by changh95** [PRBonn/MapClosures#1]
Before I begin, thank you very much for making another great software!

I just tried running MapClosures on the KITTI dataset (`map_closure_pipeline ./dataset/sequences/00/velodyne/ ./results/`)

As shown in the screenshot below, every time a new local map is made, a new line 'Creating New Local Map' gets printed, and pushes the tqdm bar to the next line. This makes many lines of tqdm monitoring lines. 

I believe this is not intended, since the original KISS-ICP had features of monitoring the progress in a single line.

Maybe we can just remove the 'creating new local map' line? or there can be a better way.

I'm still looking into the code - I will try to make a PR if I have a good idea.

![image](https://github.com/PRBonn/MapClosures/assets/39010111/506eb1d3-c096-4baf-98e0-fe7bb247f890)

**Comment by saurabh1002** [comment]
Closed with #3
