### ISSUE TITLE
Missing parameters when self._eval == False

### ISSUE THREAD

**Issue by changh95** [PRBonn/MapClosures#2]
When using a dataset without GT data, the evaluation option gets disabled.

It seems `self.closure_distance_threshold` and `self.results` are uninitialized when `self._eval` is set to False. 

Because of this, the program crashes before exiting.

![image](https://github.com/PRBonn/MapClosures/assets/39010111/776ab873-1648-416c-8ba1-1d8524a7e22d)

![image](https://github.com/PRBonn/MapClosures/assets/39010111/70df3c07-0e72-483f-97cf-6a6bf60db3f6)

**Comment by rstallman** [comment]
same problem!

**Comment by saurabh1002** [comment]
@rstallman This issue is closed by #3 thanks to @changh95
