### ISSUE TITLE
problem when -e

### ISSUE THREAD

**Issue by Snow-know-nothing** [PRBonn/MapClosures#20]
Hi, when I set `-e` parameter in the command like following:
`map_closure_pipeline --dataloader mulran  /home/barry/newspace/space1/Mulran/KAIST01/ ./results`
I will meet the problem :
![图片](https://github.com/PRBonn/MapClosures/assets/62021553/55efc028-d627-4b0a-8aef-ac810842f546)
![图片](https://github.com/PRBonn/MapClosures/assets/62021553/0d461c91-cdf2-4cc4-a7f1-2d81b8b16e29)
I haven't figured it out

**Comment by saurabh1002** [comment]
Thanks @Snow-know-nothing for pointing out the bug. We are working on this in PR  #21.
Should be fixed soon.
