### ISSUE TITLE
Result visualization without GT, PGO

### ISSUE THREAD

**Issue by frapit** [PRBonn/MapClosures#23]
Thanks for another great contribution! 

I was wondering how to easily verify the results obtained by MapClosures on a custom dataset without GT candidates. Is there an easy way to visualize the results from `map_closures.txt`? How do I know from the result file which of the original point cloud ids are aggregated to a local map?

In your paper you mention a g2o pipeline to do PGO with the odometry constraints from KISS-ICP and Loop-Closure constraints from MapClosures. Do you happen to have this evaluation part open sourced as well? It would be very convenient if all odometry and loop closure constraints could be exported in a way that it could be imported into a PG backend right away.

Thanks!

**Comment by saurabh1002** [comment]
@frapit thanks for your interest in our work.

There is a beta version of a visualizer for the loop closures on the [gupta/visualizer](https://github.com/PRBonn/MapClosures/tree/gupta/visualizer) branch of this repo, this will show a live view of KISS-ICP odometry and the generated local maps for loop closure, and upon detection of a loop closure, it will open another visualizer window in which you can navigate through all the subsequent closures and inspect them visually.

This visualizer is still under development (you can contribute by testing it out ;), and opening another issue if it does not work for you).

**Comment by saurabh1002** [comment]
I will add the g2o evaluation pipeline script soon with the proper instructions to install the g2o dependency as well, almost forgot to do that. Thanks for pointing it out!!

**Comment by saurabh1002** [comment]
Also, for the individual scans contained within each local map, we store it within the `LocalMap` class defined in the 'evaluation.py' file. The first scan index corresponding to each local map is also dumped in the `map_closures.txt` file generated at the termination of the pipeline.

![image](https://github.com/user-attachments/assets/637522cd-94d6-4dbc-bebc-f5b0651174a9)
![image](https://github.com/user-attachments/assets/7ad56b55-15ae-4cd3-a84f-ea067489057b)

**Comment by frapit** [comment]
Thanks a lot for the detailed reply. I tested the visualizer branch, it worked perfectly! This is very helpful to find a good parameter set for my data. Also, thanks for the hint with the submap indices, this is very helpful as well in order to debug particular candidates.

I am looking forward to test with some PG backend script, that would be very helpful. Thanks for your commitment to making this available as well!
