### ISSUE TITLE
Large drift, tuning, optimizing the kiss_icp poses ?

### ISSUE THREAD

**Issue by Efesendil** [PRBonn/MapClosures#27]
Hello,

First of all, thank you for providing such an easy to use tool. 

My question is related to the odometry drift, i am running the python app using a folder of pcds. The kiss_icp odometry drift can be minimized for a sparse dataset using the comment at : https://github.com/PRBonn/kiss-icp/issues/128#issuecomment-1505258331. However i would like to know if there is a way to correct the trajectory or poses obtained from kiss_icp rather then running the pipeline of map_clousre_pipeline by default, since the drift is too large for my dataset without tuning parameters. 

Thank you again, and waiting for your answer.

**Comment by saurabh1002** [comment]
Hey @Efesendil, thanks for showing interest in our work.

If I understood your issue correctly, you refer to the removal of the double downsampling [PRBonn/kiss-icp#128 (comment)](https://github.com/PRBonn/kiss-icp/issues/128#issuecomment-1505258331). Sadly, this can only be done by editing the KISS-ICP pipeline source code, and not via tha `map_closures_pipeline`. You can only change the `KISSConfig` parameters through the `pipeline.py` file here.
