### ISSUE TITLE
Question about the evaluation method

### ISSUE THREAD

**Issue by leblond14u** [PRBonn/MapClosures#39]
Hi,

Thanks for your great work. 
I have a question on the evaluation method in your MapClosure implementation. 

If I understood correctly the first output (see below) is printing the map-closure
id, the base density map, the matched density map and the estimation of the transformation between the two.
 ![image](https://github.com/user-attachments/assets/29223b67-ec5d-4651-9f14-fa1f22137893)
However I do not understand the following print : 
![image](https://github.com/user-attachments/assets/8827f078-8de0-4380-8f7f-16645a241278)
How are the True positive etc. computed ? Can you shed some light on this ?
Since it relies on density maps and a ransac algorithm I can't quite figure out how it is possible to get the feature matching ground truth ...

Thanks in advance,
Best regards,

Hugo

**Comment by saurabh1002** [comment]
Hey @leblond14u 

Thanks for showing interest in our work.

1. You got the first table right, that is the actual output of our pipeline.
2. The second table is a bit complicated, since to compare with existing approaches that are mainly scan-based, we had to convert map-level closures to scan-level closure indices. We do this as explained in the corresponding paper. (I am attaching some screenshots below to help you understand how we reach at those numbers in the second table.

![image](https://github.com/user-attachments/assets/0f1c1af9-60dd-41f7-99f8-bfd52cdc99cb)

**Comment by saurabh1002** [comment]
Also, in the code, [this](https://github.com/PRBonn/MapClosures/blob/8b4ba0d25f8471aa9fdd886f0cb84b25729bc9fc/python/map_closures/tools/evaluation.py#L43) is where the aforementioned computation happens:

![image](https://github.com/user-attachments/assets/3c47921e-a6eb-42e7-a9d4-8949b6900791)

I hope this helps you to understand how the second output table is generated. Let me know if you have further queries.

**Comment by leblond14u** [comment]
Thanks a lot, 
I'll read your answer with great attention :) 

Have a nice day,
Best,

Hugo

**Comment by saurabh1002** [comment]
Cool, I will close the issue for now, feel free to reopen if needed.

**Comment by leblond14u** [comment]
So just to clarify,

Given a submap, this submap is decomposed into scan pairs. Those pairs are then voxelized and voxels are considered Ground Truth as long as their Szymkiewicz-Simpson score between the scans of one pair with another one is greater than 0.5.

Then map-level wise, when a loop closure is detected between two submaps, they are also decomposed scan-wise. 
Each scan is then compared voxel-wise and their voxel score is based on the same Szymkiewicz-Simpson metric.

So **X True positive** values would mean that map-level-wise there is **X** scan-level voxels that have a similar score than the GT, the **false positives** are areas where the voxels between two scans are considered GT but were not scored as GT before and the **false negatives** areas where the scan-wise score is not considered as GT although it really is.

Is my understanding correct ?

Thanks a lot,

**Comment by saurabh1002** [comment]
Hey,

Not exactly!

#### For the Groundtruth Closures at scan-index level:
1. Given two voxelized submaps (generated using groundtruth poses) containing scan indices {a, b, c} and {j, k, l} respectively, we compute the voxel overlap score as the Szymkiewicz-Simpson score between the two voxelized submaps.
2. If this score is greater than 0.5, which means they have sufficient overlap, we take all the possible pairs of scan indices between the two sets of scan indices {a, b, c} and {j, k, l}  defining  the two submap to be the ground truth. 
3. So the gt closures set would look like {{a, j}, {a, k}, {a, l}, {b, j}, {b, k}, {b, l}, {c, j}, {c, k}, {c, l}}.

#### For the map to scan-index level conversion of detected loop closures:
1. Given two voxelized loop-closed localmaps (generated using KISS-ICP poses) containing scan indices {a, b, c} and {j, k, l} respectively, we apply the 2d pose correction obtained from our loop closure pipeline to the poses of the reference local map. 
2. After this, the two sets of poses (in the query and reference local maps) should be aligned (assuming it is a correct loop closure).
3. We do not compute any overlap metric in our loop-closure pipeline. We simply take the local map scan indices {a, b, c} and {j, k, l} respectively, along with their poses after the 2d alignment, and generate exhaustive pairs of scan indices between these two sets.
4. As an additional pruning step, we filter these pairs of scan indices by thresholding on the distance between the two (corrected) poses corresponding to the scan indices.

So the metrics such as (positives, negatives) are not the number of overlapping voxels, but the overlap in the scan-index pairs space.

**Comment by leblond14u** [comment]
Ok its much clearer now !

Thanks a lot, 
Have a great day,

Hugo
