### ISSUE TITLE
May i know how to organize the Datasets?

### ISSUE THREAD

**Issue by dzrdzrdzr** [PRBonn/MapClosures#42]
For example, what are the datasets, preprocessing methods, and path organization forms

**Comment by saurabh1002** [comment]
Hello @dzrdzrdzr,

We support the datasets listed in the `python/map_closures/datasets` subfolder, i.e. **[apollo](https://apolloscape.auto/tracking.html)**, **[MulRAN](https://sites.google.com/view/mulran-pr/dataset)**, **[HeLiPR](https://sites.google.com/view/heliprdataset/home)**, **[ncd](https://ori-drs.github.io/newer-college-dataset/stereo-cam/)**, **[kitti](https://www.cvlibs.net/datasets/kitti/eval_odometry.php)**. You can just download the dataset with their default directory structure and pass the path of the directory location to our pipeline, along with the dataloader flag, for example `--dataloader <name-of-dataloader>. Use `map_closure_pipeline --help` to see more information about the CLI usage.

Additionally, we provide **rosbag** and **mcap** dataloader to process pointclouds directly from ROS1/2 bag files, you only have to provide the path to the bag, and the `sensor_msgs/PointCloud2` topic name to be used.

Finally, there is the **generic** dataloader, which can be used to read a variety of pointcloud file formats in the provided file path. You can see in `generic.py` the different pointcloud formats supported.

Regarding the preprocessing methods, it is handled by the main pipeline in the same way for all datasets, which is only a `max_range` filtering.

This beautiful dataloader structure has been taken from [KISS-ICP](https://github.com/PRBonn/kiss-icp)!!

**Comment by dzrdzrdzr** [comment]
So rosbag isn't necessary? It can read the dataset directly

**Comment by saurabh1002** [comment]
Yes, it can read the above mentioned datasets directly, no need to convert them to rosbags.
