### ISSUE TITLE
How to use it in my own c++ project? Any example?

### ISSUE THREAD

**Issue by G4419** [PRBonn/MapClosures#46]

**Comment by saurabh1002** [comment]
Hello @G4419, have you already tried the instructions for the same as provided in the project README?

**Comment by G4419** [comment]
I mean, how to use these functions which in map_closures/MapClosures.hpp.

**Comment by saurabh1002** [comment]
Okay! For that only one function is required from `MapClosures.hpp`.

```cpp
ClosureCandidate MatchAndAdd(const int id, const std::vector<Eigen::Vector3d> &local_map);
```
This function takes in a `local_map` as a `std::vector<Eigen::Vector3d>` PointCloud, along with an associated `id` which is the index of this local map.
It will return a type `ClosureCandidate` which is a struct containing the `source` and `target` local_map `id`, the initial guess `pose` aligning them based on the RANSAC alignment strategy in the paper, and the `number_of_inliers` obtained in the RANSAC scheme.


If no closure is detected, this struct will have its default values as in the definition of the same.

**Comment by saurabh1002** [comment]
The above mentioned function handles all the other steps internally, i.e.
1. Generates the Density BEV Image
2. Computes ORB Features
3. Matches these features to any existing features in the HBST database from previously seen local maps, and uses these matches for a RANSAC alignment and makes a decision if a closure is found or not
4. Finally, irrespective of whether or not a closure was found, we add the features from the latest local map into the HBST database with its associated `id`

**Comment by G4419** [comment]
Thank you for your prompt and detailed response. I will try to implement it in my project.
