### ISSUE TITLE
Question about matching density maps with ORB features

### ISSUE THREAD

**Issue by leblond14u** [PRBonn/MapClosures#49]
Hi, 

I'm trying to replicate your idea in a simple python code to match density maps which contains an overlap with each other. 
I took parts from the scenes of kitti360 which conveniently provide a GT cloud, selected a few ~100 meters sequences with ~20 meters of overlap. I then converted the point-clouds to normalized density maps (see image attached). 
However when computing ORB features and trying to match them I'm having difficulties to get a good translation and rotation estimation with kabsch_umeyama and ransac. 
![density_map_z_V2](https://github.com/user-attachments/assets/1e93fab0-9241-4780-a02a-df2238af6e63)
![density_map_z_V2](https://github.com/user-attachments/assets/34722712-6b51-4473-b2c1-cd47dbdc5607)

Do I need to increase the overlap in between my scenes to get better results ? 
Also could you point me to the exact parameters you used for the **ransac** algorithm ?

Thanks a lot in advance,
Best regards,

Hugo

**Comment by saurabh1002** [comment]
Hey @leblond14u ,
The parameters for the ORB Features are set in the `MapClosures.cpp` file and for the RANSAC algorithm in the `AlignRansac2D.cpp` file.

Did you try the pipeline provided here on the KITTI360 dataset you are using?

It would be nice to take a look at your python code to understand what you are doing, and possibly help you.

**Comment by saurabh1002** [comment]
So I assume that the python script equivalent of our approach works. In that case I will close this issue.

Regarding the learning-based features, it can be done. We did not find the ORB features to be a bottleneck so far on the various sequences we have tried. We had also tried other features such as SIFT during the early development stage of this project, which worked equally well. We want to keep the pipeline as simple as possible without requiring any learning-based components unless absolutely necessary.

In case you try something else, I would be happy to hear about how they perform, just keep in mind that the HBST database we use requires binary feature descriptors, so you might need to modify Superpoint or change the database.

**Comment by leblond14u** [comment]
Ok thanks for those insights ! 

I'll try other approaches, I'll be happy to collaborate with you if there's anything interesting to dig ;)

Have a nice day,
Best,

Hugo

**Comment by saurabh1002** [comment]
The rotation invariance of ORB works quite well for us.
Even though we use KISS-ICP for odometry, we have the local maps in a local reference frame of the first scan in the map. So the odometry information is only local to that frame. As a result we do have closures with 180 degree rotations, and ORB features do a good job to allow us identify them correctly.

**Comment by saurabh1002** [comment]
Let me know how your research with other approaches for feature detection progresses.
Will be more than happy to collaborate :)
